### ISSUE TITLE
Docker image seems to not be publicly available

### ISSUE THREAD

**Issue by ShadF0x** [wegwerfen/flocap#7]
Tried pulling the Docker image as per instructions, and all I get is this message:

```
Unable to find image 'ghcr.io/wegwerfen/flocap:cpu' locally
docker: Error response from daemon: denied.
See 'docker run --help'.
```
Trying to access the ghcr link directly through the browser returns 404.
![image](https://github.com/wegwerfen/flocap/assets/38113636/549c26ac-08b7-4f5f-9793-5c1e8c809784)

**Comment by wegwerfen** [comment]
Sorry for the delay.

The package visibility has been corrected and is available now.
